/**
 * @file invitations.ts
 * @description Mini README: Holds seed invitation records so the auth workflow can demonstrate issuance, tracking, and
 * redemption. Invitations mimic secure, expiring tokens generated by platform administrators. Each record references the
 * intended role and any preselected organisation.
 */

import type { InvitationRecord } from '@/types/platform';

export const seedInvitations: InvitationRecord[] = [
  {
    code: 'FF-USER-TRIAL-001',
    email: 'new.collaborator@fusionfutures.example',
    role: 'user',
    issuedBy: 'account-admin-001',
    issuedAt: '2024-05-01T12:00:00.000Z',
    // Extend expiry well into the future so the shared invite link remains valid during demos.
    expiresAt: '2026-06-01T12:00:00.000Z',
    status: 'pending',
    organisationNameSuggestion: 'Aurora Fusion Labs',
    message: 'Join to co-design employer projects and propose your new organisation.'
  },
  {
    code: 'FF-ADMIN-BOOST-001',
    email: 'ops.manager@fusionfutures.example',
    role: 'admin',
    issuedBy: 'account-superadmin-001',
    issuedAt: '2024-04-20T09:15:00.000Z',
    // Likewise keep the admin onboarding invite usable for guided walkthroughs.
    expiresAt: '2026-05-25T09:15:00.000Z',
    status: 'pending',
    organisationId: 'org-ops-001',
    message: 'Help oversee onboarding approvals for the operations team.'
  }
];
