# ============================================================================
# File: .github/workflows/ci.yml
# Purpose: Continuous integration pipeline running linting, testing, and type generation.
# Structure: Defines matrix across Node and Python to ensure compatibility.
# Usage: Triggered on pull requests and pushes to main.
# ============================================================================
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -e services/api[dev]
      - name: Lint
        run: . .venv/bin/activate && ruff check services/api/src
      - name: Format check
        run: . .venv/bin/activate && black --check services/api/src
      - name: Tests
        run: . .venv/bin/activate && pytest

  types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Generate Types
        run: |
          corepack enable
          pnpm install
          node scripts/generate-types.mjs || true
